services:
  - type: web
    name: url-threat-checker-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: url-threat-checker-db
          property: connectionString
      - key: BACKEND_CORS_ORIGINS
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD_HASH
        value: "pbkdf2_sha256$260000$dXJsLXRocmVhdC1kZW1vLXNhbHQ$9y9jpBrb-hPXQU35h0SLyc2XOU7gFxVXFVmqFWNtuc4"
      - key: TOTP_SECRET
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false

databases:
  - name: url-threat-checker-db
    databaseName: url_threat_checker
    plan: free
